### ISSUE TITLE
Typo in Cargo.toml description: "ect"

### ISSUE THREAD

**Issue by tv42** [Jackboxx/progressed#1]
Hi, I was browsing progress bar things and noticed a spelling error, it says "ect":

https://github.com/lucifayr/progressed/blob/107196c3e026a4658420da868523e5c895eebfc3/Cargo.toml#L7

**Comment by lucifayr** [comment]
Hey, thanks for taking the time to leave a comment. I'll merge a fix into main.

**Comment by lucifayr** [comment]
https://github.com/lucifayr/progressed/commit/07272dc5830c0750fec3def82603cc57b4b705c5
